#!/bin/sh

echo "Speculos Wrapper called with $*"

for last in "$@"; do :; done

case $last in
  *ts_tests*)
    echo "Matched *ts_tests*"
    speculos "$@" --display headless &
    SPECULOS=$!
    until wget -O/dev/null -o/dev/null http://localhost:5000/; do sleep 0.1; done;
    cd ../ts-tests;
    if ! [ -d "node_modules" ] ; then npm install; fi
    npm test
    kill $SPECULOS
    ;;
  */deps/*) # Assume anything in the deps directory is a test, not the full app.
    echo "Matched *tests*"
    speculos "$@" --display headless ;;
  *) speculos "$@" ;;
esac
