#!/usr/bin/env bash

echo "Speculos Wrapper called with $*"

# Specify args for mocha / 'yarn run test' like this
# cargo test --test ts-tests --target=nanos.json -- --mocha-args="--grep 'provides a public key'"
# cargo test --test ts-tests --target=nanos.json -- --mocha-args="--timeout 30000"
MOCHA_ARGS=""

API_PORT=5005

run_ts_tests() {
    speculos --api-port "$API_PORT" "$@" --display headless &
    SPECULOS=$!
    until wget -O/dev/null -o/dev/null http://localhost:$API_PORT/; do sleep 0.1; done;
    cd ../ts-tests;
    if ! [ -d "node_modules" ] ; then yarn install; fi
    echo $MOCHA_ARGS | xargs yarn run test --
    kill $SPECULOS
}

last="${@:$#}"

case $last in
  --mocha-args=*)
    echo "Matched --mocha-args=*"
    MOCHA_ARGS=${last:13} # strip --mocha-args=
    echo "Passing following args to yarn run test: $MOCHA_ARGS"
    # Pass all args, except the last, to the speculos
    run_ts_tests "${@:1:$#-1}"
    ;;
  *ts_tests*)
    echo "Matched *ts_tests*"
    run_ts_tests "$@"
    ;;
  */deps/*) # Assume anything in the deps directory is a test, not the full app.
    echo "Matched *tests*"
    speculos --api-port "$API_PORT" "$@" --display headless ;;
  *) speculos --api-port "$API_PORT" "$@" ;;
esac
