# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@cspotcode/source-map-support-0.8.1" = {
      name = "_at_cspotcode_slash_source-map-support";
      packageName = "@cspotcode/source-map-support";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspotcode/source-map-support/-/source-map-support-0.8.1.tgz";
        sha512 = "IchNf6dN4tHoMFIn/7OE8LWZ19Y6q/67Bmf6vnGREv8RSbBVb9LPJxEcnwrcwX6ixSvaiGoomAUvu4YSxXrVgw==";
      };
    };
    "@jridgewell/resolve-uri-3.0.7" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.0.7.tgz";
        sha512 = "8cXDaBBHOr2pQ7j77Y6Vp5VDT2sIqWyWQ56TjEq4ih/a4iST3dItRe8Q9fp0rrIl9DoKhWQtUQz/YpOxLkXbNA==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.13" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.13.tgz";
        sha512 = "GryiOJmNcWbovBxTfZSF71V/mXbgcV3MewDe3kIMCLyIh5e7SKAeUZs+rMnJ8jkMolZ/4/VsdBmMrw3l+VdZ3w==";
      };
    };
    "@jridgewell/trace-mapping-0.3.9" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.9.tgz";
        sha512 = "3Belt6tdc8bPgAtbcmdtNJlirVoTmEb5e2gC94PnkwEW9jI6CAHUeoG85tjWP5WquqfavoMtMwiG4P926ZKKuQ==";
      };
    };
    "@ledgerhq/devices-6.27.1" = {
      name = "_at_ledgerhq_slash_devices";
      packageName = "@ledgerhq/devices";
      version = "6.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ledgerhq/devices/-/devices-6.27.1.tgz";
        sha512 = "jX++oy89jtv7Dp2X6gwt3MMkoajel80JFWcdc0HCouwDsV1mVJ3SQdwl/bQU0zd8HI6KebvUP95QTwbQLLK/RQ==";
      };
    };
    "@ledgerhq/errors-6.10.0" = {
      name = "_at_ledgerhq_slash_errors";
      packageName = "@ledgerhq/errors";
      version = "6.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ledgerhq/errors/-/errors-6.10.0.tgz";
        sha512 = "fQFnl2VIXh9Yd41lGjReCeK+Q2hwxQJvLZfqHnKqWapTz68NHOv5QcI0OHuZVNEbv0xhgdLhi5b65kgYeQSUVg==";
      };
    };
    "@ledgerhq/hw-transport-6.27.1" = {
      name = "_at_ledgerhq_slash_hw-transport";
      packageName = "@ledgerhq/hw-transport";
      version = "6.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ledgerhq/hw-transport/-/hw-transport-6.27.1.tgz";
        sha512 = "hnE4/Fq1YzQI4PA1W0H8tCkI99R3UWDb3pJeZd6/Xs4Qw/q1uiQO+vNLC6KIPPhK0IajUfuI/P2jk0qWcMsuAQ==";
      };
    };
    "@ledgerhq/hw-transport-node-speculos-6.7.0" = {
      name = "_at_ledgerhq_slash_hw-transport-node-speculos";
      packageName = "@ledgerhq/hw-transport-node-speculos";
      version = "6.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ledgerhq/hw-transport-node-speculos/-/hw-transport-node-speculos-6.7.0.tgz";
        sha512 = "RgFom5N6XLQ3xSl+pFWZmmxQxsBdAVJTpyPoClYNoH/ETif2gQHRE1AhtYpSHeJRRMUsioZEMSqW3l8qqdjclA==";
      };
    };
    "@ledgerhq/logs-6.10.0" = {
      name = "_at_ledgerhq_slash_logs";
      packageName = "@ledgerhq/logs";
      version = "6.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ledgerhq/logs/-/logs-6.10.0.tgz";
        sha512 = "lLseUPEhSFUXYTKj6q7s2O3s2vW2ebgA11vMAlKodXGf5AFw4zUoEbTz9CoFOC9jS6xY4Qr8BmRnxP/odT4Uuw==";
      };
    };
    "@tsconfig/node10-1.0.9" = {
      name = "_at_tsconfig_slash_node10";
      packageName = "@tsconfig/node10";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node10/-/node10-1.0.9.tgz";
        sha512 = "jNsYVVxU8v5g43Erja32laIDHXeoNvFEpX33OK4d6hljo3jDhCBDhx5dhCCTMWUojscpAagGiRkBKxpdl9fxqA==";
      };
    };
    "@tsconfig/node12-1.0.11" = {
      name = "_at_tsconfig_slash_node12";
      packageName = "@tsconfig/node12";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node12/-/node12-1.0.11.tgz";
        sha512 = "cqefuRsh12pWyGsIoBKJA9luFu3mRxCA+ORZvA4ktLSzIuCUtWVxGIuXigEwO5/ywWFMZ2QEGKWvkZG1zDMTag==";
      };
    };
    "@tsconfig/node14-1.0.3" = {
      name = "_at_tsconfig_slash_node14";
      packageName = "@tsconfig/node14";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node14/-/node14-1.0.3.tgz";
        sha512 = "ysT8mhdixWK6Hw3i1V2AeRqZ5WfXg1G43mqoYlM2nc6388Fq5jcXyr5mRsqViLx/GJYdoL0bfXD8nmF+Zn/Iow==";
      };
    };
    "@tsconfig/node16-1.0.3" = {
      name = "_at_tsconfig_slash_node16";
      packageName = "@tsconfig/node16";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node16/-/node16-1.0.3.tgz";
        sha512 = "yOlFc+7UtL/89t2ZhjPvvB/DeAr3r+Dq58IgzsFkOAvVC6NMJXmCGjbptdXdR9qsX7pKcTL+s87FtYREi2dEEQ==";
      };
    };
    "@types/chai-4.3.1" = {
      name = "_at_types_slash_chai";
      packageName = "@types/chai";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/chai/-/chai-4.3.1.tgz";
        sha512 = "/zPMqDkzSZ8t3VtxOa4KPq7uzzW978M9Tvh+j7GHKuo6k6GTLxPJ4J5gE5cjfJ26pnXst0N5Hax8Sr0T2Mi9zQ==";
      };
    };
    "@types/js-nacl-1.3.0" = {
      name = "_at_types_slash_js-nacl";
      packageName = "@types/js-nacl";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/js-nacl/-/js-nacl-1.3.0.tgz";
        sha512 = "juUvxo444ZfwDSwWyhssMxSN+snqTdiUoOVXZF+/ffVrGHq3rAf1fmczWn3z9TCEAuRbaTmgAcYlZ9MutyyOkQ==";
      };
    };
    "@types/mocha-9.1.1" = {
      name = "_at_types_slash_mocha";
      packageName = "@types/mocha";
      version = "9.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mocha/-/mocha-9.1.1.tgz";
        sha512 = "Z61JK7DKDtdKTWwLeElSEBcWGRLY8g95ic5FoQqI9CMx0ns/Ghep3B4DfcEimiKMvtamNVULVNKEsiwV3aQmXw==";
      };
    };
    "@types/node-16.11.41" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "16.11.41";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-16.11.41.tgz";
        sha512 = "mqoYK2TnVjdkGk8qXAVGc/x9nSaTpSrFaGFm43BUH3IdoBV0nta6hYaGmdOvIMlbHJbUEVen3gvwpwovAZKNdQ==";
      };
    };
    "@types/node-fetch-3.0.3" = {
      name = "_at_types_slash_node-fetch";
      packageName = "@types/node-fetch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node-fetch/-/node-fetch-3.0.3.tgz";
        sha512 = "HhggYPH5N+AQe/OmN6fmhKmRRt2XuNJow+R3pQwJxOOF9GuwM7O2mheyGeIrs5MOIeNjDEdgdoyHBOrFeJBR3g==";
      };
    };
    "@ungap/promise-all-settled-1.1.2" = {
      name = "_at_ungap_slash_promise-all-settled";
      packageName = "@ungap/promise-all-settled";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ungap/promise-all-settled/-/promise-all-settled-1.1.2.tgz";
        sha512 = "sL/cEvJWAnClXw0wHk85/2L0G6Sj8UB0Ctc1TEMbKSsmpRosqhwj9gWgFRZSrBr2f9tiXISwNhCPmlfqUqyb9Q==";
      };
    };
    "acorn-8.7.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.7.1.tgz";
        sha512 = "Xx54uLJQZ19lKygFXOWsscKUbsBZW0CPykPhVQdhIeIwrbPmJzqeASDInc8nKBnp/JT6igTs82qPXz069H8I/A==";
      };
    };
    "acorn-walk-8.2.0" = {
      name = "acorn-walk";
      packageName = "acorn-walk";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-walk/-/acorn-walk-8.2.0.tgz";
        sha512 = "k+iyHEuPgSw6SbuDpGQM+06HQUa04DZ3o+F6CSzXMvvI5KMvnaEqXe+YVe555R9nn6GPt404fos4wcgpw12SDA==";
      };
    };
    "ansi-colors-4.1.1" = {
      name = "ansi-colors";
      packageName = "ansi-colors";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.1.tgz";
        sha512 = "JoX0apGbHaUJBNl6yF+p6JAFYZ666/hhCGKN5t9QFjbJQKUU/g8MNbFDbvfrgKXvI1QpZplPOnwIo99lX/AAmA==";
      };
    };
    "ansi-regex-3.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.1.tgz";
        sha512 = "+O9Jct8wf++lXxxFc4hc8LsjaSq0HFzzL7cVsw8pRDIPdjKD2mT4ytDZlLuSBZ4cLKZFXIrMGO7DbQCtMJJMKw==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "anymatch-3.1.2" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.2.tgz";
        sha512 = "P43ePfOAIupkguHUycrc4qJ9kz8ZiuOUijaETwX7THt0Y/GNK7v0aa8rY816xWjZ7rJdA5XdMcpVFTKMq+RvWg==";
      };
    };
    "arg-4.1.3" = {
      name = "arg";
      packageName = "arg";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/arg/-/arg-4.1.3.tgz";
        sha512 = "58S9QDqG0Xx27YwPSt9fJxivjYl432YCwfDMfZ+71RAqUrZef7LrKQZ3LHLOwCS4FLNBplP533Zx895SeOCHvA==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "assertion-error-1.1.0" = {
      name = "assertion-error";
      packageName = "assertion-error";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assertion-error/-/assertion-error-1.1.0.tgz";
        sha512 = "jgsaNduz+ndvGyFt3uSuWqvy4lCnIJiovtouQN5JZHOKCS2QuhEdbcQHFhVksz2N2U9hXJo8odG7ETyWlEeuDw==";
      };
    };
    "axios-0.22.0" = {
      name = "axios";
      packageName = "axios";
      version = "0.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.22.0.tgz";
        sha512 = "Z0U3uhqQeg1oNcihswf4ZD57O3NrR1+ZXhxaROaWpDmsDTx7T2HNBV2ulBtie2hwJptu8UvgnJoK+BIqdzh/1w==";
      };
    };
    "b4a-1.5.3" = {
      name = "b4a";
      packageName = "b4a";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/b4a/-/b4a-1.5.3.tgz";
        sha512 = "1aCQIzQJK7G0z1Una75tWMlwVAR8o+QHoAlnWc5XAxRVBESY9WsitfBgM5nPyDBP5HrhPU1Np4Pq2Y7CJQ+tVw==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "binary-extensions-2.2.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.2.0.tgz";
        sha512 = "jDctJ/IVQbZoJykoeHbhXpOlNBqGNcwXJKJog42E5HDPUwQTSdjCHdihjj0DlnheQ7blbT6dHOafNAiS8ooQKA==";
      };
    };
    "bip32-path-0.4.2" = {
      name = "bip32-path";
      packageName = "bip32-path";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip32-path/-/bip32-path-0.4.2.tgz";
        sha512 = "ZBMCELjJfcNMkz5bDuJ1WrYvjlhEF5k6mQ8vUr4N7MbVRsXei7ZOg8VhhwMfNiW68NWmLkgkc6WvTickrLGprQ==";
      };
    };
    "blake2b-2.1.4" = {
      name = "blake2b";
      packageName = "blake2b";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/blake2b/-/blake2b-2.1.4.tgz";
        sha512 = "AyBuuJNI64gIvwx13qiICz6H6hpmjvYS5DGkG6jbXMOT8Z3WUJ3V1X0FlhIoT1b/5JtHE3ki+xjtMvu1nn+t9A==";
      };
    };
    "blake2b-wasm-2.4.0" = {
      name = "blake2b-wasm";
      packageName = "blake2b-wasm";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/blake2b-wasm/-/blake2b-wasm-2.4.0.tgz";
        sha512 = "S1kwmW2ZhZFFFOghcx73+ZajEfKBqhP82JMssxtLVMxlaPea1p9uoLiUZ5WYyHn0KddwbLc+0vh4wR0KBNoT5w==";
      };
    };
    "bn.js-5.2.1" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.2.1.tgz";
        sha512 = "eXRvHzWyYPBuB4NBy0cmYQjGitUrtqwbvlzP3G6VFnNRbsZQIxQ10PbKKHt8gZ/HW/D/747aDl+QkDqg3KQLMQ==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "browser-stdout-1.3.1" = {
      name = "browser-stdout";
      packageName = "browser-stdout";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-stdout/-/browser-stdout-1.3.1.tgz";
        sha512 = "qhAVI1+Av2X7qelOfAIYwXONood6XlZE/fXaBSmW/T5SzLAmCgzi+eiWE7fUvbHaeNBQH13UftjpXxsfLkMpgw==";
      };
    };
    "camelcase-6.3.0" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-6.3.0.tgz";
        sha512 = "Gmy6FhYlCY7uOElZUSbxo2UCDH8owEk996gkbrpsgGtrJLM3J7jGxl9Ic7Qwwj4ivOE5AWZWRMecDdF7hqGjFA==";
      };
    };
    "chai-4.3.6" = {
      name = "chai";
      packageName = "chai";
      version = "4.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/chai/-/chai-4.3.6.tgz";
        sha512 = "bbcp3YfHCUzMOvKqsztczerVgBKSsEijCySNlHHbX3VG1nskvqjz5Rfso1gGwD6w6oOV3eI60pKuMOV5MV7p3Q==";
      };
    };
    "chai-bytes-0.1.2" = {
      name = "chai-bytes";
      packageName = "chai-bytes";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chai-bytes/-/chai-bytes-0.1.2.tgz";
        sha512 = "0ol6oJS0y1ozj6AZK8n1pyv1/G+l44nqUJygAkK1UrYl+IOGie5vcrEdrAlwmLYGIA9NVvtHWosPYwWWIXf/XA==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "check-error-1.0.2" = {
      name = "check-error";
      packageName = "check-error";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/check-error/-/check-error-1.0.2.tgz";
        sha512 = "BrgHpW9NURQgzoNyjfq0Wu6VFO6D7IZEmJNdtgNqpzGG8RuNFHt2jQxWlAs4HMe119chBnv+34syEZtc6IhLtA==";
      };
    };
    "child_process-1.0.2" = {
      name = "child_process";
      packageName = "child_process";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/child_process/-/child_process-1.0.2.tgz";
        sha512 = "Wmza/JzL0SiWz7kl6MhIKT5ceIlnFPJX+lwUGj7Clhy5MMldsSoJR0+uvRzOS5Kv45Mq7t1PoE8TsOA9bzvb6g==";
      };
    };
    "chokidar-3.5.1" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.5.1.tgz";
        sha512 = "9+s+Od+W0VJJzawDma/gvBNQqkTiqYTWLuZoyAsivsI4AaWTCzHG06/TMjsf1cYe9Cb97UCEhjz7HvnPk2p/tw==";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "cliui-7.0.4" = {
      name = "cliui";
      packageName = "cliui";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-7.0.4.tgz";
        sha512 = "OcRE68cOsVMXp1Yvonl/fzkQOyjLSu/8bhPDfQt0e0/Eb283TKP20Fs2MqoPsr9SwA595rRCA+QMzYc9nBP+JQ==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 = "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-require-1.1.1" = {
      name = "create-require";
      packageName = "create-require";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-require/-/create-require-1.1.1.tgz";
        sha512 = "dcKFX3jn0MpIaXjisoRvexIJVEKzaq7z2rZKxf+MSr9TkdmHmsU4m2lcLojrj/FHl8mk5VxMmYA+ftRkP/3oKQ==";
      };
    };
    "data-uri-to-buffer-4.0.0" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-4.0.0.tgz";
        sha512 = "Vr3mLBA8qWmcuschSLAOogKgQ/Jwxulv3RNE4FXnYWRGujzrRWQI4m12fQqRkwX06C0KanhLr4hK+GydchZsaA==";
      };
    };
    "debug-4.3.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.1.tgz";
        sha512 = "doEwdvm4PCeK4K3RQN2ZC2BYUBaxwLARCqZmMjtF8a51J2Rb0xpVloFRnCODwqjpwnAoao4pelN8l3RJdv3gRQ==";
      };
    };
    "decamelize-4.0.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-4.0.0.tgz";
        sha512 = "9iE1PgSik9HeIIw2JO94IidnE3eBoQrFJ3w7sFuzSX4DpmZ3v5sZpUiV5Swcf6mQEF+Y0ru8Neo+p+nyh2J+hQ==";
      };
    };
    "deep-eql-3.0.1" = {
      name = "deep-eql";
      packageName = "deep-eql";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-eql/-/deep-eql-3.0.1.tgz";
        sha512 = "+QeIQyN5ZuO+3Uk5DYh6/1eKO0m0YmJFGNmFHGACpf1ClL1nmlV/p4gNgbl2pJGxgXb4faqo6UE+M5ACEMyVcw==";
      };
    };
    "diff-4.0.2" = {
      name = "diff";
      packageName = "diff";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-4.0.2.tgz";
        sha512 = "58lmxKSA4BNyLz+HHMUzlOEpg09FV+ev6ZMe3vJihgdxzgcwZ8VoEEPmALCZG9LmqfVoNMMKpttIYTVG6uDY7A==";
      };
    };
    "diff-5.0.0" = {
      name = "diff";
      packageName = "diff";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-5.0.0.tgz";
        sha512 = "/VTCrvm5Z0JGty/BWHljh+BAiw3IK+2j87NGMu8Nwc/f48WoDAC395uomO9ZD117ZOBaHmkX1oyLvkVM/aIT3w==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "events-3.3.0" = {
      name = "events";
      packageName = "events";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-3.3.0.tgz";
        sha512 = "mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==";
      };
    };
    "fast-check-2.25.0" = {
      name = "fast-check";
      packageName = "fast-check";
      version = "2.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-check/-/fast-check-2.25.0.tgz";
        sha512 = "wRUT2KD2lAmT75WNIJIHECawoUUMHM0I5jrlLXGtGeqmPL8jl/EldUDjY1VCp6fDY8yflyfUeIOsOBrIbIiArg==";
      };
    };
    "fast-sha256-1.3.0" = {
      name = "fast-sha256";
      packageName = "fast-sha256";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-sha256/-/fast-sha256-1.3.0.tgz";
        sha512 = "n11RGP/lrWEFI/bWdygLxhI+pVeo1ZYIVwvvPkW7azl/rOy+F3HYRZ2K5zeE9mmkhQppyv9sQFx0JM9UabnpPQ==";
      };
    };
    "fetch-blob-3.1.5" = {
      name = "fetch-blob";
      packageName = "fetch-blob";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fetch-blob/-/fetch-blob-3.1.5.tgz";
        sha512 = "N64ZpKqoLejlrwkIAnb9iLSA3Vx/kjgzpcDhygcqJ2KKjky8nCgUQ+dzXtbrLaWZGZNmNfQTsiQ0weZ1svglHg==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "find-up-5.0.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-5.0.0.tgz";
        sha512 = "78/PXT1wlLLDgTzDs7sjq9hzz0vXD+zn+7wypEe4fXQxCmdmqfGsEPQxmiCSQI3ajFV91bVSsvNtrJRiW6nGng==";
      };
    };
    "flat-5.0.2" = {
      name = "flat";
      packageName = "flat";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/flat/-/flat-5.0.2.tgz";
        sha512 = "b6suED+5/3rTpUBdG1gupIl8MPFCAMA0QXwmljLhvCUKcUvdE4gWky9zpuGCcXHOsz4J9wPGNWq6OKpmIzz3hQ==";
      };
    };
    "follow-redirects-1.15.1" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.1.tgz";
        sha512 = "yLAMQs+k0b2m7cVxpS1VKJVvoz7SS9Td1zss3XRwXj+ZDH00RJgnuLx7E44wx02kQLrdM3aOOy+FpzS7+8OizA==";
      };
    };
    "formdata-polyfill-4.0.10" = {
      name = "formdata-polyfill";
      packageName = "formdata-polyfill";
      version = "4.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/formdata-polyfill/-/formdata-polyfill-4.0.10.tgz";
        sha512 = "buewHzMvYL29jdeQTVILecSaZKnt/RJWjoZCF5OW60Z67/GmSLBkOFM7qh1PI3zFNtJbaZL5eQu1vLfazOwj4g==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "get-func-name-2.0.0" = {
      name = "get-func-name";
      packageName = "get-func-name";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-func-name/-/get-func-name-2.0.0.tgz";
        sha512 = "Hm0ixYtaSZ/V7C8FJrtZIuBBI+iSgL+1Aq82zSu8VQNB4S3Gk8e7Qs3VwBDJAhmRZcFqkl3tQu36g/Foh5I5ig==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "glob-8.0.3" = {
      name = "glob";
      packageName = "glob";
      version = "8.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-8.0.3.tgz";
        sha512 = "ull455NHSHI/Y1FqGaaYFaLGkNMMJbavMrEGFXG/PGrg6y7sutWHUHrz6gy6WEBH6akM1M414dWKCNs+IhKdiQ==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "growl-1.10.5" = {
      name = "growl";
      packageName = "growl";
      version = "1.10.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/growl/-/growl-1.10.5.tgz";
        sha512 = "qBr4OuELkhPenW6goKVXiv47US3clb3/IbuWF9KNKEijAy9oeHxU9IgzjvJhHkUzhaj7rOUD7+YGWqUjLp5oSA==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hash-base-3.1.0" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.1.0.tgz";
        sha512 = "1nmYp/rhMDiE7AYkDw+lLwlAzz0AntGIe51F3RfFfEqyQ3feY2eI/NcwC6umIQVOASPMsWJLJScWKSSvzL9IVA==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "hw-app-obsidian-common-git+https://github.com/obsidiansystems/hw-app-obsidian-common.git#9c4c397861e33761f2e5f5af29bb6642a05fd9e1" = {
      name = "hw-app-obsidian-common";
      packageName = "hw-app-obsidian-common";
      version = "0.0.1";
      src = fetchgit {
        url = "https://github.com/obsidiansystems/hw-app-obsidian-common.git";
        rev = "9c4c397861e33761f2e5f5af29bb6642a05fd9e1";
        sha256 = "199b0519c4b1f12509ed4c853252838341310ada23d085f6e8bda773e9ad2d65";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-fullwidth-code-point-2.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha512 = "VHskAKYM8RfSFXwee5t5cbN5PZeq1Wrh6qd5bkyiXIf6UQcN6w/A0eXM9r6t8d+GYOh+o6ZhiEnb88LN/Y8m2w==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-plain-obj-2.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-2.1.0.tgz";
        sha512 = "YWnfyRwxL/+SsrWYfOpUtz5b3YD+nyfkHvjbcanzk8zgyO4ASD67uVMRt8k5bM4lLMDnXfriRhOpemw+NfT1eA==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "js-nacl-1.4.0" = {
      name = "js-nacl";
      packageName = "js-nacl";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-nacl/-/js-nacl-1.4.0.tgz";
        sha512 = "HgYLcutGbMYBJrwgVICiHliuw1OJLy2U3tIuK6a1rZ06KC84TPl81WG1hcBRrBCiIIuBe3PSo9G4IZOMGdSg3Q==";
      };
    };
    "js-yaml-4.0.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.0.0.tgz";
        sha512 = "pqon0s+4ScYUvX30wxQi3PogGFAlUyH0awepWvwkj4jD4v+ova3RiYw8bmA6x2rDrEaj8i/oWKoRxpVNW+Re8Q==";
      };
    };
    "jsonc-parser-3.0.0" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.0.0.tgz";
        sha512 = "fQzRfAbIBnR0IQvftw9FJveWiHp72Fg20giDrHz6TdfB12UH/uue0D3hm57UB5KgAVuniLMCaS8P1IMj9NR7cA==";
      };
    };
    "locate-path-6.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-6.0.0.tgz";
        sha512 = "iPZK6eYjbxRu3uB4/WZ3EsEIMJFMqAoopl3R+zuq0UjcAm/MO6KCweDgPfP3elTztoKP3KtnVHxTn2NHBSDVUw==";
      };
    };
    "log-symbols-4.0.0" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-4.0.0.tgz";
        sha512 = "FN8JBzLx6CzeMrB0tg6pqlGU1wCrXW+ZXGH481kfsBqer0hToTIiHdjH4Mq8xJUbvATujKCvaREGWpGUionraA==";
      };
    };
    "loupe-2.3.4" = {
      name = "loupe";
      packageName = "loupe";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/loupe/-/loupe-2.3.4.tgz";
        sha512 = "OvKfgCC2Ndby6aSTREl5aCCPTNIzlDfQZvZxNUrBrihDhL3xcrYegTblhmEiCrg2kKQz4XsFIaemE5BF4ybSaQ==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "lunr-2.3.9" = {
      name = "lunr";
      packageName = "lunr";
      version = "2.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/lunr/-/lunr-2.3.9.tgz";
        sha512 = "zTU3DaZaF3Rt9rhN3uBMGQD3dD2/vFQqnvZCDv4dl5iOzq2IZQqTxu90r4E5J+nP70J3ilqVCrbho2eWaeW8Ow==";
      };
    };
    "make-error-1.3.6" = {
      name = "make-error";
      packageName = "make-error";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-error/-/make-error-1.3.6.tgz";
        sha512 = "s8UhlNe7vPKomQhC1qFelMokr/Sc3AgNbso3n74mVPA5LTZwkB9NlXf4XPamLxJE8h0gh73rM94xvwRT2CVInw==";
      };
    };
    "marked-4.0.17" = {
      name = "marked";
      packageName = "marked";
      version = "4.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-4.0.17.tgz";
        sha512 = "Wfk0ATOK5iPxM4ptrORkFemqroz0ZDxp5MWfYA7H/F+wO17NRWV5Ypxi6p3g2Xmw2bKeiYOl6oVnLHKxBA0VhA==";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 = "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimatch-5.1.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-5.1.0.tgz";
        sha512 = "9TPBGGak4nHfGZsPBohm9AWg6NoT7QTCehS3BIJABslyZbzxfV78QM2Y6+i741OPZIafFAaiiEMh5OyIrJPgtg==";
      };
    };
    "mocha-8.4.0" = {
      name = "mocha";
      packageName = "mocha";
      version = "8.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mocha/-/mocha-8.4.0.tgz";
        sha512 = "hJaO0mwDXmZS4ghXsvPVriOhsxQ7ofcpQdm8dE+jISUOKopitvnXFQmpRR7jd2K6VBG6E26gU3IAbXXGIbu4sQ==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "nanoassert-2.0.0" = {
      name = "nanoassert";
      packageName = "nanoassert";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoassert/-/nanoassert-2.0.0.tgz";
        sha512 = "7vO7n28+aYO4J+8w96AzhmU8G+Y/xpPDJz/se19ICsqj/momRbb9mh9ZUtkoJ5X3nTnPdhEJyc0qnM6yAsHBaA==";
      };
    };
    "nanoid-3.1.20" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.1.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.1.20.tgz";
        sha512 = "a1cQNyczgKbLX9jwbS/+d7W8fX/RfgYR7lVWwWOGIPNgK2m0MWvrGF6/m4kk6U3QcFMnZf3RIhL0v2Jgh/0Uxw==";
      };
    };
    "node-domexception-1.0.0" = {
      name = "node-domexception";
      packageName = "node-domexception";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-domexception/-/node-domexception-1.0.0.tgz";
        sha512 = "/jKZoMpw0F8GRwl4/eLROPA3cfcXtLApP0QzLmUT/HuPCZWyB7IY9ZrMeKw2O/nFIqPQB3PVM9aYm0F312AXDQ==";
      };
    };
    "node-fetch-3.2.6" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-3.2.6.tgz";
        sha512 = "LAy/HZnLADOVkVPubaxHDft29booGglPFDr2Hw0J1AercRh01UiVFm++KMDnJeH9sHgNB4hsXPii7Sgym/sTbw==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "p-limit-3.1.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-3.1.0.tgz";
        sha512 = "TYOanM3wGwNGsZN2cVTYPArw454xnXj5qmWF1bEoAc4+cU/ol7GVh7odevjp1FNHduHc3KZMcFduxU5Xc6uJRQ==";
      };
    };
    "p-locate-5.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-5.0.0.tgz";
        sha512 = "LaNjtRWUBY++zB5nE/NwcaoMylSPk+S+ZHNB1TzdbMJMny6dynpAGt7X/tl/QYq3TIeE6nxHppbo2LGymrG5Pw==";
      };
    };
    "path-exists-4.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
        sha512 = "ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "pathval-1.1.1" = {
      name = "pathval";
      packageName = "pathval";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pathval/-/pathval-1.1.1.tgz";
        sha512 = "Dp6zGqpTdETdR63lehJYPeIOqpiNBNtc7BpWSLrOje7UaIsE5aY92r/AunQA7rsXvet3lrJ3JnZX29UPTKXyKQ==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pure-rand-5.0.1" = {
      name = "pure-rand";
      packageName = "pure-rand";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pure-rand/-/pure-rand-5.0.1.tgz";
        sha512 = "ksWccjmXOHU2gJBnH0cK1lSYdvSZ0zLoCMSz/nTGh6hDvCSgcRxDyIcOBD6KNxFz3xhMPm/T267Tbe2JRymKEQ==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "readdirp-3.5.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.5.0.tgz";
        sha512 = "cMhu7c/8rdhkHXWsY+osBhfSy0JikwpHK/5+imo+LpeasTF8ouErHrlYkwT0++njiyuDvc7OFY5T3ukvZ8qmFQ==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha512 = "fGxEI7+wsG9xrvdjsrlmL22OMTTiHRwAMroiEeMgq8gzoLC/PQr7RsRDSTLUg/bZAZtF+TVIkHc6/4RIKrui+Q==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 = "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "rxjs-6.6.7" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "6.6.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-6.6.7.tgz";
        sha512 = "hTdwr+7yYNIT5n4AMYp85KA6yw2Va0FLa3Rguvbpa4W3I5xynaBZo41cM3XM+4Q6fRMj3sBYIR1VAmZMXYJvRQ==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "serialize-javascript-5.0.1" = {
      name = "serialize-javascript";
      packageName = "serialize-javascript";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialize-javascript/-/serialize-javascript-5.0.1.tgz";
        sha512 = "SaaNal9imEO737H2c05Og0/8LUXG7EnsZyMa8MzkmuHoELfT6txuj0cMqRj6zfPKnmQ1yasR4PCJc8x+M4JSPA==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "shiki-0.10.1" = {
      name = "shiki";
      packageName = "shiki";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shiki/-/shiki-0.10.1.tgz";
        sha512 = "VsY7QJVzU51j5o1+DguUd+6vmCmZ5v/6gYu4vyYAhzjuNQU6P/vmSy4uQaOhvje031qQMiW0d2BwgMH52vqMng==";
      };
    };
    "string-width-2.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
        sha512 = "nOqH59deCq9SRHlxq1Aw85Jnt4w6KvLKqWVik6oA9ZklXLNIOlqg4F2yrT1MVaTjAqvVwdfeZ7w7aCvJD7ugkw==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-4.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha512 = "4XaJ2zQdCzROZDivEVIDPkcQn8LMFSa8kj8Gxb/Lnwzv9A8VctNZ+lfivC/sV3ivW8ElJTERXZoPBRrZKkNKow==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-json-comments-3.1.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
        sha512 = "6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "ts-node-10.8.1" = {
      name = "ts-node";
      packageName = "ts-node";
      version = "10.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-node/-/ts-node-10.8.1.tgz";
        sha512 = "Wwsnao4DQoJsN034wePSg5nZiw4YKXf56mPIAeD6wVmiv+RytNSWqc2f3fKvcUoV+Yn2+yocD71VOfQHbmVX4g==";
      };
    };
    "tslib-1.14.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz";
        sha512 = "Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg==";
      };
    };
    "type-detect-4.0.8" = {
      name = "type-detect";
      packageName = "type-detect";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-detect/-/type-detect-4.0.8.tgz";
        sha512 = "0fr/mIH1dlO+x7TlcMy+bIDqKPsw/70tVyeHW787goQjhmqaZe10uwLujubK9q9Lg6Fiho1KUKDYz0Z7k7g5/g==";
      };
    };
    "typedoc-0.22.17" = {
      name = "typedoc";
      packageName = "typedoc";
      version = "0.22.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedoc/-/typedoc-0.22.17.tgz";
        sha512 = "h6+uXHVVCPDaANzjwzdsj9aePBjZiBTpiMpBBeyh1zcN2odVsDCNajz8zyKnixF93HJeGpl34j/70yoEE5BfNg==";
      };
    };
    "typescript-4.7.4" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.7.4.tgz";
        sha512 = "C0WQT0gezHuw6AdY1M2jxUO83Rjf0HP7Sk1DtXj6j1EwkQNZrHAg2XPWlq62oqEhYvONq5pkC2Y9oPljWToLmQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "v8-compile-cache-lib-3.0.1" = {
      name = "v8-compile-cache-lib";
      packageName = "v8-compile-cache-lib";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8-compile-cache-lib/-/v8-compile-cache-lib-3.0.1.tgz";
        sha512 = "wa7YjyUGfNZngI/vtK0UHAN+lgDCxBPCylVXGp0zu59Fz5aiGtNXaq3DhIov063MorB+VfufLh3JlF2KdTK3xg==";
      };
    };
    "vscode-oniguruma-1.6.2" = {
      name = "vscode-oniguruma";
      packageName = "vscode-oniguruma";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-oniguruma/-/vscode-oniguruma-1.6.2.tgz";
        sha512 = "KH8+KKov5eS/9WhofZR8M8dMHWN2gTxjMsG4jd04YhpbPR91fUj7rYQ2/XjeHCJWbg7X++ApRIU9NUwM2vTvLA==";
      };
    };
    "vscode-textmate-5.2.0" = {
      name = "vscode-textmate";
      packageName = "vscode-textmate";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-textmate/-/vscode-textmate-5.2.0.tgz";
        sha512 = "Uw5ooOQxRASHgu6C7GVvUxisKXfSgW4oFlO+aa+PAkgmH89O3CXxEEzNRNtHSqtXFTl0nAC1uYj0GMSH27uwtQ==";
      };
    };
    "web-streams-polyfill-3.2.1" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-3.2.1.tgz";
        sha512 = "e0MO3wdXWKrLbL0DgGnUV7WHVuw9OUvL4hjgnPkIeEvESk74gAITi5G606JtZPp39cd8HA9VQzCIvA49LpPN5Q==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wide-align-1.1.3" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.3.tgz";
        sha512 = "QGkOQc8XL6Bt5PwnsExKBPuMKBxnGxWWW3fU55Xt4feHozMUhdUMaBCk290qpm/wG5u/RSKzwdAC4i51YigihA==";
      };
    };
    "workerpool-6.1.0" = {
      name = "workerpool";
      packageName = "workerpool";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/workerpool/-/workerpool-6.1.0.tgz";
        sha512 = "toV7q9rWNYha963Pl/qyeZ6wG+3nnsyvolaNUS8+R5Wtw6qJPTxIlOP1ZSvcGhEJw+l3HMMmtiNo9Gl61G4GVg==";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-16.2.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "16.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-16.2.0.tgz";
        sha512 = "D1mvvtDG0L5ft/jGWkLpG1+m0eQxOfaBvTNELraWj22wSVUMWxZUvYgJYcKh6jGGIkJFhH4IZPQhR4TKpc8mBw==";
      };
    };
    "yargs-parser-20.2.4" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "20.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-20.2.4.tgz";
        sha512 = "WOkpgNhPTlE73h4VFAFsOnomJVaovO8VqLDzy5saChRBFQFBoMYirowyW+Q9HB4HFF4Z7VZTiG3iSzJJA29yRA==";
      };
    };
    "yargs-unparser-2.0.0" = {
      name = "yargs-unparser";
      packageName = "yargs-unparser";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-unparser/-/yargs-unparser-2.0.0.tgz";
        sha512 = "7pRTIA9Qc1caZ0bZ6RYRGbHJthJWuakf+WmHK0rVeLkNrrGhfoabBNdue6kdINI6r4if7ocq9aD/n7xwKOdzOA==";
      };
    };
    "yn-3.1.1" = {
      name = "yn";
      packageName = "yn";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yn/-/yn-3.1.1.tgz";
        sha512 = "Ux4ygGWsu2c7isFWe8Yu1YluJmqVhxqK2cLXNQA5AcC3QfbGNpM7fu0Y8b/z16pXLnFxZYvWhd3fhBY9DLmC6Q==";
      };
    };
    "yocto-queue-0.1.0" = {
      name = "yocto-queue";
      packageName = "yocto-queue";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz";
        sha512 = "rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==";
      };
    };
  };
  args = {
    name = "rust-app-ledger-tests";
    packageName = "rust-app-ledger-tests";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."@cspotcode/source-map-support-0.8.1"
      sources."@jridgewell/resolve-uri-3.0.7"
      sources."@jridgewell/sourcemap-codec-1.4.13"
      sources."@jridgewell/trace-mapping-0.3.9"
      sources."@ledgerhq/devices-6.27.1"
      sources."@ledgerhq/errors-6.10.0"
      sources."@ledgerhq/hw-transport-6.27.1"
      sources."@ledgerhq/hw-transport-node-speculos-6.7.0"
      sources."@ledgerhq/logs-6.10.0"
      sources."@tsconfig/node10-1.0.9"
      sources."@tsconfig/node12-1.0.11"
      sources."@tsconfig/node14-1.0.3"
      sources."@tsconfig/node16-1.0.3"
      sources."@types/chai-4.3.1"
      sources."@types/js-nacl-1.3.0"
      sources."@types/mocha-9.1.1"
      sources."@types/node-16.11.41"
      sources."@types/node-fetch-3.0.3"
      sources."@ungap/promise-all-settled-1.1.2"
      sources."acorn-8.7.1"
      sources."acorn-walk-8.2.0"
      sources."ansi-colors-4.1.1"
      sources."ansi-regex-3.0.1"
      sources."ansi-styles-4.3.0"
      sources."anymatch-3.1.2"
      sources."arg-4.1.3"
      sources."argparse-2.0.1"
      sources."assertion-error-1.1.0"
      sources."axios-0.22.0"
      sources."b4a-1.5.3"
      sources."balanced-match-1.0.2"
      sources."binary-extensions-2.2.0"
      sources."bip32-path-0.4.2"
      sources."blake2b-2.1.4"
      sources."blake2b-wasm-2.4.0"
      sources."bn.js-5.2.1"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."browser-stdout-1.3.1"
      sources."camelcase-6.3.0"
      sources."chai-4.3.6"
      sources."chai-bytes-0.1.2"
      (sources."chalk-4.1.2" // {
        dependencies = [
          sources."supports-color-7.2.0"
        ];
      })
      sources."check-error-1.0.2"
      sources."child_process-1.0.2"
      sources."chokidar-3.5.1"
      sources."cipher-base-1.0.4"
      (sources."cliui-7.0.4" // {
        dependencies = [
          sources."ansi-regex-5.0.1"
          sources."is-fullwidth-code-point-3.0.0"
          sources."string-width-4.2.3"
          sources."strip-ansi-6.0.1"
        ];
      })
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."concat-map-0.0.1"
      sources."create-hash-1.2.0"
      sources."create-require-1.1.1"
      sources."data-uri-to-buffer-4.0.0"
      (sources."debug-4.3.1" // {
        dependencies = [
          sources."ms-2.1.2"
        ];
      })
      sources."decamelize-4.0.0"
      sources."deep-eql-3.0.1"
      sources."diff-5.0.0"
      sources."emoji-regex-8.0.0"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-4.0.0"
      sources."events-3.3.0"
      sources."fast-check-2.25.0"
      sources."fast-sha256-1.3.0"
      sources."fetch-blob-3.1.5"
      sources."fill-range-7.0.1"
      sources."find-up-5.0.0"
      sources."flat-5.0.2"
      sources."follow-redirects-1.15.1"
      sources."formdata-polyfill-4.0.10"
      sources."fs.realpath-1.0.0"
      sources."fsevents-2.3.2"
      sources."get-caller-file-2.0.5"
      sources."get-func-name-2.0.0"
      sources."glob-7.1.6"
      sources."glob-parent-5.1.2"
      sources."growl-1.10.5"
      sources."has-flag-4.0.0"
      sources."hash-base-3.1.0"
      sources."he-1.2.0"
      sources."hw-app-obsidian-common-git+https://github.com/obsidiansystems/hw-app-obsidian-common.git#9c4c397861e33761f2e5f5af29bb6642a05fd9e1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-binary-path-2.1.0"
      sources."is-extglob-2.1.1"
      sources."is-fullwidth-code-point-2.0.0"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."is-plain-obj-2.1.0"
      sources."isexe-2.0.0"
      sources."js-nacl-1.4.0"
      sources."js-yaml-4.0.0"
      sources."jsonc-parser-3.0.0"
      sources."locate-path-6.0.0"
      sources."log-symbols-4.0.0"
      sources."loupe-2.3.4"
      sources."lru-cache-6.0.0"
      sources."lunr-2.3.9"
      sources."make-error-1.3.6"
      sources."marked-4.0.17"
      sources."md5.js-1.3.5"
      sources."minimatch-3.0.4"
      sources."mocha-8.4.0"
      sources."ms-2.1.3"
      sources."nanoassert-2.0.0"
      sources."nanoid-3.1.20"
      sources."node-domexception-1.0.0"
      sources."node-fetch-3.2.6"
      sources."normalize-path-3.0.0"
      sources."once-1.4.0"
      sources."p-limit-3.1.0"
      sources."p-locate-5.0.0"
      sources."path-exists-4.0.0"
      sources."path-is-absolute-1.0.1"
      sources."pathval-1.1.1"
      sources."picomatch-2.3.1"
      sources."pure-rand-5.0.1"
      sources."randombytes-2.1.0"
      sources."readable-stream-3.6.0"
      sources."readdirp-3.5.0"
      sources."require-directory-2.1.1"
      sources."ripemd160-2.0.2"
      sources."rxjs-6.6.7"
      sources."safe-buffer-5.2.1"
      sources."semver-7.3.7"
      sources."serialize-javascript-5.0.1"
      sources."sha.js-2.4.11"
      sources."shiki-0.10.1"
      sources."string-width-2.1.1"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-4.0.0"
      sources."strip-json-comments-3.1.1"
      sources."supports-color-8.1.1"
      sources."to-regex-range-5.0.1"
      (sources."ts-node-10.8.1" // {
        dependencies = [
          sources."diff-4.0.2"
        ];
      })
      sources."tslib-1.14.1"
      sources."type-detect-4.0.8"
      (sources."typedoc-0.22.17" // {
        dependencies = [
          sources."brace-expansion-2.0.1"
          sources."glob-8.0.3"
          sources."minimatch-5.1.0"
        ];
      })
      sources."typescript-4.7.4"
      sources."util-deprecate-1.0.2"
      sources."v8-compile-cache-lib-3.0.1"
      sources."vscode-oniguruma-1.6.2"
      sources."vscode-textmate-5.2.0"
      sources."web-streams-polyfill-3.2.1"
      sources."which-2.0.2"
      sources."wide-align-1.1.3"
      sources."workerpool-6.1.0"
      (sources."wrap-ansi-7.0.0" // {
        dependencies = [
          sources."ansi-regex-5.0.1"
          sources."is-fullwidth-code-point-3.0.0"
          sources."string-width-4.2.3"
          sources."strip-ansi-6.0.1"
        ];
      })
      sources."wrappy-1.0.2"
      sources."y18n-5.0.8"
      sources."yallist-4.0.0"
      (sources."yargs-16.2.0" // {
        dependencies = [
          sources."ansi-regex-5.0.1"
          sources."is-fullwidth-code-point-3.0.0"
          sources."string-width-4.2.3"
          sources."strip-ansi-6.0.1"
        ];
      })
      sources."yargs-parser-20.2.4"
      sources."yargs-unparser-2.0.0"
      sources."yn-3.1.1"
      sources."yocto-queue-0.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
