/*
 * Speculos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Apdu {
    /// APDU data, in hexadecimal.
    #[serde(rename = "data")]
    pub data: String,
}

impl Apdu {
    pub fn new(data: String) -> Apdu {
        Apdu {
            data,
        }
    }
}


