/*
 * Speculos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Button {
    /// Press, release or press and release the specified button(s).
    #[serde(rename = "action")]
    pub action: Action,
    /// Delay in seconds between press and release, ignored if action isn't `press-and-released`.
    #[serde(rename = "delay", skip_serializing_if = "Option::is_none")]
    pub delay: Option<f32>,
}

impl Button {
    pub fn new(action: Action) -> Button {
        Button {
            action,
            delay: None,
        }
    }
}

/// Press, release or press and release the specified button(s).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "press")]
    Press,
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "press-and-release")]
    PressAndRelease,
}

