/*
 * Speculos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Finger {
    /// Press, release or press and release.
    #[serde(rename = "action")]
    pub action: Action,
    /// Vertical position
    #[serde(rename = "x")]
    pub x: i32,
    /// Horizontal position
    #[serde(rename = "y")]
    pub y: i32,
    /// Delay in seconds between press and release, ignored if action isn't `press-and-released`.
    #[serde(rename = "delay", skip_serializing_if = "Option::is_none")]
    pub delay: Option<f32>,
}

impl Finger {
    pub fn new(action: Action, x: i32, y: i32) -> Finger {
        Finger {
            action,
            x,
            y,
            delay: None,
        }
    }
}

/// Press, release or press and release.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "press")]
    Press,
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "press-and-release")]
    PressAndRelease,
}

